Vagrant.configure("2") do |config|
  config.vm.guest = :windows
  config.vm.communicator = :winrm    
  
  config.vm.box = "Microsoft/EdgeOnWindows10"
  config.vm.box_version = "1.0"   
  
  #config.ssh.insert_key = false
  #config.vm.network "private_network", ip: "192.168.56.15"
  config.vm.network "private_network", type: "dhcp"
  config.vm.network "forwarded_port", host: 33389, guest: 3389, id: "rdp", auto_correct: true
  
  #config.vm.network :forwarded_port, guest: 22, host: 1234
  
  #config.ssh.password = "vagrant"
  #config.ssh.username = "vagrant" 
  config.ssh.username = "IEUser"
  config.ssh.password = "Passw0rd!"
  
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.synced_folder "app/", "/app"
  
  config.vm.provider "virtualbox" do |v|
	v.name = "ELECTRONWIN"
	v.gui = false  
    v.memory = 8192
	v.cpus = 2
	v.customize ["modifyvm", :id, "--vram", "256"]
	#--nictype<1-N> Am79C970A|Am79C973|82540EM|82543GC|82545EM|virtio
	v.default_nic_type = "82540EM"
  end
  config.vm.provision :shell, path: "FirstRun.ps1"  
  config.vm.provision :shell, path: "Programs.ps1"
  config.vm.provision :shell, path: "Node.ps1"
end

#PC NAME  = IE11WIN10
#LOGIN    = IE11WIN10\IEUser
#Password = Passw0rd!
#(Run As Administrator) => slmgr /rearm 