Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/precise64"

  config.vm.network "private_network", ip: "192.168.56.4"
  
  config.vm.network :forwarded_port, guest: 3000, host: 3000
  config.vm.network :forwarded_port, guest: 80, host: 8080
  
  config.ssh.forward_agent = true
  
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.synced_folder 'app/', '/home/vagrant'
  
  config.vm.provider "virtualbox" do |v|
	v.name = "REACT"
	v.gui = false  
    v.memory = 1024
  end
  
  config.vm.provision :shell, path: "provision.sh"
end
