Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"

  config.ssh.insert_key = false

  config.vm.network "private_network", ip: "192.168.56.5"
  config.vm.network :forwarded_port, guest: 80, host: 8080      # apache/nginx
   
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.synced_folder "app/", "/var/www"
  
  config.vm.provider "virtualbox" do |v|
	v.name = "APACHE"
	v.gui = false  
    v.memory = 2048
  end
  config.vm.provision :shell, path: "php.sh"
  config.vm.provision :shell, path: "mysql.sh"
end
