FROM ubuntu

RUN apt-get update && apt-get install -y \
    g++ \
    git \
    libxml2-dev \
    libxslt-dev \
    wget \
    make \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir Projetos
WORKDIR /Projetos/

RUN wget ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre-8.42.tar.gz && tar -zxf pcre-8.42.tar.gz \
    && wget http://zlib.net/zlib-1.2.11.tar.gz && tar -zxf zlib-1.2.11.tar.gz \
    && wget http://www.openssl.org/source/openssl-1.0.2o.tar.gz && tar -zxf openssl-1.0.2o.tar.gz \
    && wget https://nginx.org/download/nginx-1.14.0.tar.gz && tar zxf nginx-1.14.0.tar.gz \
    && git clone https://github.com/jcu-eresearch/nginx-custom-build.git 

WORKDIR /Projetos/pcre-8.42/
RUN ./configure \
   && make \
   && make install

WORKDIR /Projetos/zlib-1.2.11/
RUN ./configure \
    && make \
    && make install

WORKDIR /Projetos/nginx-1.14.0/
RUN patch -p1 < ../nginx-custom-build/nginx-xslt-html-parser.patch

RUN ./configure --with-pcre --with-http_xslt_module --with-http_ssl_module --with-openssl=../openssl-1.0.2o/ \
    && make \
    && make install

WORKDIR /Projetos/	
	
RUN rm -rf /Projetos/*

ENV PATH /usr/local/nginx/sbin/:$PATH