Vagrant.configure("2") do |config|
  #PRIVATE BOX WINDOWS 7 / DELPHI BERLIN / ACBR
  config.vm.box = "DELPHIBERLIN"

  config.ssh.insert_key = false
  config.vm.network "private_network", ip: "192.168.56.7"
  
  #config.vm.network :forwarded_port, guest: 22, host: 1234
  
  #config.ssh.forward_agent = true
  
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.synced_folder "app/", "/app"
  
  config.vm.provider "virtualbox" do |v|
	v.name = "DELPHIBERLIN"
	v.gui = false  
    v.memory = 8192
	v.cpus = 2
	v.customize ["modifyvm", :id, "--vram", "256"]
	#--nictype<1-N> Am79C970A|Am79C973|82540EM|82543GC|82545EM|virtio
	v.default_nic_type = "82540EM"	
  end

end
