Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"

  config.ssh.insert_key = false
  
  config.vm.network "public_network", ip: "192.168.1.18"

  config.vm.network :forwarded_port, guest: 8080, host: 8080
  
  config.ssh.forward_agent = false
  
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.synced_folder "app/", "/var/www"
  
  config.vm.provider "virtualbox" do |v|
	v.name = "ZAMMAD"
	v.gui = false  
    v.memory = 4096
  end
  
  config.vm.provision :shell, path: "bootstrap.sh"
end
