FROM ubuntu:14.04

MAINTAINER Saulo Nunes

COPY script.sh /script.sh

CMD ["/script.sh"]
#COPY provision.sh /provision.sh
#COPY nginx.sh /nginx.sh

#CMD ["/provision.sh"]
#CMD ["/nginx.sh"]

#COPY default /etc/nginx/sites-available/default

#CMD service nginx start && service php5-fpm start && /bin/bash