Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  
  config.vm.network "private_network", ip: "192.168.56.4"
  
  config.vm.network :forwarded_port, guest: 3000, host: 3000
  config.vm.network :forwarded_port, guest: 80, host: 8080
  config.vm.network :forwarded_port, guest: 8081, host: 8081  
  config.vm.network :forwarded_port, guest: 443, host: 443  
  
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.synced_folder "app/", "/Projetos"
  
  config.vm.provider "virtualbox" do |v|
	v.name = "DOCKER"
	v.gui = false  
	v.memory = 2048
  end  
end
