Vagrant.configure("2") do |config|
  #PRIVATE BOX WINDOWS 7 / DELPHI 7 / FIREBIRD 2.5
  config.vm.box = "DELPHI7FB25"

  config.ssh.insert_key = false
  
  config.vm.network "private_network", ip: "192.168.56.7"
  
  #config.ssh.forward_agent = true
  
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.synced_folder "app/", "/app"
  
  config.vm.provider "virtualbox" do |v|
	v.name = "DELPHI7FB25"
	v.gui = false  
    v.memory = 8192
	v.customize ["modifyvm", :id, "--vram", "256"]
  end

end
